name: Abuse of Microsoft Office Applications
criticality: Medium
metadata:
  uuid: b663b684-a80f-4570-89b6-2f7faa16fece
  schema: threat::1.0
  version: 1
  created: 2024-10-31
  modified: 2024-10-31
  tlp: clear
  organisation:
    uuid: 56b0a0f0-b0bc-47d9-bb46-02f80ae2065a
    name: EC DIGIT CSOC
threat:
  actors:
    - att&ck::G0007
    - misp::5b4ee3ea-eee3-4c8e-8323-85ae32658754
    - att&ck::G0016
    - misp::2ee5ed7a-c4d0-40be-a837-20817474a15b
    - att&ck::G0046
    - misp::00220228-a5a4-4032-a30d-826bb55aa3fb
    - att&ck::G0092
    - misp::03c80674-35f8-4fe0-be2b-226ed0fcd69f
    - att&ck::G0102
    - misp::3c2bb7d7-a085-4594-adc7-4a20cf724abb
  killchain: Execution
  att&ck:
    - T1059.005
    - T1204.002
    - T1137
    - T1203
  chaining:
    - relation: sequence::succeeds
      vector: dd5d942c-bac4-4000-b9a6-ca4fef6cfb84
      description: Most of malware comes from email attachment and can be executed afterwards
  terrain: |-
    Target systems must have Microsoft Office applications installed with macros 
    enabled or be susceptible to social engineering tactics that prompt users 
    to enable macros or execute malicious content.
  severity: Moderate incident
  leverage: Spoofing; Tampering; Information Disclosure; Elevation of privilege; Software installation
  impact: Data Breach; IP Loss; Identity Theft; Business disruption
  viability: Very Likely
  description: |-
    An employee named receives an email that appears to be from a trusted business 
    partner or colleague. The email contains an office document. The end-user clic on it.

    The attached file, is a macro-enabled Word document. It usually pops-up with 
    the following message :
    "This document was created in an earlier version of Microsoft Word. 
    Please click 'Enable Content' above to view the full document."

    This message is designed to entice end-user to enable macros or active content, 
    which is disabled by default for security reasons.

    By clicking ont it, it allows the embedded macro, written in 
    Visual Basic for Applications (VBA), to execute without further prompts.

    Once executed, the macro initiates a hidden process that launches Windows PowerShell, 
    which run:

    - Run silently without displaying a window to the user.
    - Bypass execution policies that normally restrict script running.
    - Connect to an external server controlled by the attacker.
    - Download and execute additional malicious code or a payload.

    Threat actors may also modify Windows Registry settings related to 
    Microsoft Office security.

    - Disabling the COM Kill Bit: This involves changing registry values 
    that control the activation of certain COM objects or ActiveX controls 
    within Office applications. By disabling the "kill bit," the threat actor 
    re-enables outdated or vulnerable components that can be exploited.

    - Altering Macro Security Settings: Changing registry keys to lower the 
    macro security level, allowing macros to run without prompts in the future.

    To maintain long-term access to the compromised system, 
    the attacker may target Microsoft Outlook.

    - Embedding Malicious Code in Outlook's VBA Project:
    - The attacker adds VBA code to Outlook's VbaProject.otm file.
    This code executes every time Outlook starts, performing actions without the user's knowledge.
  surface:
    - Windows
    - Microsoft::Microsoft 365
    - Microsoft::SharePoint
    - Microsoft::Outlook
    - Email
    - Windows::Desktop
    - File Sharing
